#Python e Numpy
(https://numpy.org/)

Os arquivos de dados utilizados foram fornecidos pelo curso "Python para Data Science" do Alura. E estão na pasta "data\python_numpy"



*   Arrays nunmpy
*Alguns atributos e métodos de arrays numpy





In [2]:
import numpy as np

In [4]:
km = np.loadtxt('carros-km.txt', dtype = int) #criando um array a partir de um arquivo txt

In [5]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [6]:
km.shape #dimensões do array

(258,)

In [7]:
anos = np.loadtxt('carros-anos.txt', dtype = int)

In [8]:
km_anos = np.array([km, anos]) #array de duas dimensões

In [9]:
km_anos

array([[ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
         99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
         46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
             0,      0,   5795,      0,  58848,  94381,  30163,  53332,
         17720,  33808,  90684,  43975,      0,      0,   5526,      0,
         93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
             0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
        119513,      0,      0,      0,      0,      0, 118895,  48509,
        100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
         54395,  26731,  44329, 118236, 113808,    610,      0,      0,
         12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
             0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
        110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
         26544,  52596,  47503,  89056,  28834, 110564,  56638, 

In [11]:
km_anos.shape

(2, 258)

In [12]:
km_por_ano = km_anos[0]/(2021 - km_anos[1]) #operação de quilometragem média de cada carro entre os km rodados e a idade

In [13]:
km_por_ano

array([2.46722222e+03, 1.90400000e+02, 1.19751613e+03, 0.00000000e+00,
       1.71713333e+03, 1.19200000e+03, 0.00000000e+00, 6.46658333e+03,
       9.01790909e+03, 3.79780000e+03, 6.76789474e+02, 5.75142857e+02,
       4.48865000e+03, 0.00000000e+00, 3.45475000e+03, 2.31214000e+04,
       5.16100000e+03, 0.00000000e+00, 7.41720000e+03, 3.79325000e+03,
       5.32594737e+03, 0.00000000e+00, 3.63255556e+03, 3.43196667e+03,
       0.00000000e+00, 0.00000000e+00, 1.15900000e+03, 0.00000000e+00,
       3.09726316e+03, 3.14603333e+03, 1.25679167e+03, 2.05123077e+03,
       5.90666667e+03, 1.12693333e+03, 1.29548571e+04, 1.69134615e+03,
       0.00000000e+00, 0.00000000e+00, 4.60500000e+02, 0.00000000e+00,
       1.16768750e+04, 2.26455556e+03, 0.00000000e+00, 4.54221053e+03,
       0.00000000e+00, 5.13421053e+02, 4.11441176e+03, 1.19750000e+02,
       0.00000000e+00, 4.46383333e+03, 7.12950000e+03, 3.36640000e+03,
       3.22457143e+03, 6.26313333e+03, 3.21318182e+03, 3.00025926e+03,
      

In [14]:
km_anos[:, 0:5] #acessando as duas linhas e as colunas de 0 a 5 (array['linhas','colunas'])

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [15]:
anos[anos > 2000] #selecionando os anos mairoes que 2000

array([2003, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002, 2007, 2001,
       2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019, 2019, 2019,
       2016, 2019, 2002, 2018, 2014, 2019, 2019, 2009, 2019, 2013, 2003,
       2019, 2002, 2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2006,
       2010, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 2019,
       2019, 2007, 2007, 2006, 2013, 2008, 2008, 2019, 2019, 2007, 2019,
       2019, 2016, 2011, 2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003,
       2003, 2004, 2010, 2019, 2006, 2001, 2019, 2015, 2018, 2017, 2001,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 2019, 2019, 2009, 2003, 2019, 2019, 2015, 2019, 2019,
       2019, 2019, 2012, 2007, 2013, 2002, 2015, 2013, 2013, 2009, 2019,
       2019, 2002, 2004, 2015, 2016, 2005, 2004, 2013, 2018, 2019, 2018,
       2019, 2009, 2006, 2002, 2019, 2019, 2005, 2010, 2019, 2016, 2019,
       2010, 2001, 2014, 2001, 2019, 2019, 2019, 20

In [17]:
km_anos[:, km_anos[1] > 2000] #acessando km apenas de anos maiores que 2000

array([[ 44410,      0,  25757,  10728,      0,  77599,  99197,  37978,
         12859,   8052,  89773,      0,  41457, 115607,  46449,      0,
         37086,  15173, 101193,      0,      0,      0,   5795,      0,
         58848,  17720,  90684,      0,      0,   5526,      0,  93415,
         40762,      0,  86302,      0,   9755,  69945,   2395,      0,
         80349,  85554,  50496,  93947,  35345, 119513,      0,      0,
             0,      0,      0, 118895,  48509, 100912,      0,      0,
         29132,  84992,  26731,  44329, 113808,    610,      0,      0,
         79607,      0,      0, 117714, 113885,      0,  30511,  74867,
        119760,   8356,  64247,  88661,   4539, 110116,  33215,  92001,
             0,  81708,  70641,      0,  91277,  26544,  52596,  89056,
         56638,  17357,  74015,  15196,      0,  10821,      0,      0,
          9595,  99052,  52389, 119945,  96005,      0,      0,  58212,
         61672,      0,      0,  86519,      0,      0,      0, 

In [18]:
km_anos.T #transposição do conjunto de dados também pode ser .transpose()

array([[ 44410,   2003],
       [  5712,   1991],
       [ 37123,   1990],
       [     0,   2019],
       [ 25757,   2006],
       [ 10728,   2012],
       [     0,   2019],
       [ 77599,   2009],
       [ 99197,   2010],
       [ 37978,   2011],
       [ 12859,   2002],
       [  8052,   2007],
       [ 89773,   2001],
       [     0,   2019],
       [ 41457,   2009],
       [115607,   2016],
       [ 46449,   2012],
       [     0,   2019],
       [ 37086,   2016],
       [ 15173,   2017],
       [101193,   2002],
       [     0,   2019],
       [ 98079,   1994],
       [102959,   1991],
       [     0,   2019],
       [     0,   2019],
       [  5795,   2016],
       [     0,   2019],
       [ 58848,   2002],
       [ 94381,   1991],
       [ 30163,   1997],
       [ 53332,   1995],
       [ 17720,   2018],
       [ 33808,   1991],
       [ 90684,   2014],
       [ 43975,   1995],
       [     0,   2019],
       [     0,   2019],
       [  5526,   2009],
       [     0,   2019],


In [33]:
km_anos2 = np.concatenate((km, anos)) #concatena os arrays km e anos

In [34]:
km_anos2 #array unidimensional gerado

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [36]:
km_anos2.reshape((km.size, 2), order = 'F') #muda a forma do array unidimensional para 2d organizando pares (km, ano)

array([[ 44410,   2003],
       [  5712,   1991],
       [ 37123,   1990],
       [     0,   2019],
       [ 25757,   2006],
       [ 10728,   2012],
       [     0,   2019],
       [ 77599,   2009],
       [ 99197,   2010],
       [ 37978,   2011],
       [ 12859,   2002],
       [  8052,   2007],
       [ 89773,   2001],
       [     0,   2019],
       [ 41457,   2009],
       [115607,   2016],
       [ 46449,   2012],
       [     0,   2019],
       [ 37086,   2016],
       [ 15173,   2017],
       [101193,   2002],
       [     0,   2019],
       [ 98079,   1994],
       [102959,   1991],
       [     0,   2019],
       [     0,   2019],
       [  5795,   2016],
       [     0,   2019],
       [ 58848,   2002],
       [ 94381,   1991],
       [ 30163,   1997],
       [ 53332,   1995],
       [ 17720,   2018],
       [ 33808,   1991],
       [ 90684,   2014],
       [ 43975,   1995],
       [     0,   2019],
       [     0,   2019],
       [  5526,   2009],
       [     0,   2019],


In [47]:
km_anos.resize((3, km.size), refcheck = False) #cria mais uma linha para o array

In [48]:
km_anos_media

array([[ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
         99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
         46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
             0,      0,   5795,      0,  58848,  94381,  30163,  53332,
         17720,  33808,  90684,  43975,      0,      0,   5526,      0,
         93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
             0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
        119513,      0,      0,      0,      0,      0, 118895,  48509,
        100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
         54395,  26731,  44329, 118236, 113808,    610,      0,      0,
         12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
             0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
        110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
         26544,  52596,  47503,  89056,  28834, 110564,  56638, 

In [49]:
km_anos[2] = km_por_ano #preeche a terceira linha com as medias

In [50]:
km_anos

array([[ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
         99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
         46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
             0,      0,   5795,      0,  58848,  94381,  30163,  53332,
         17720,  33808,  90684,  43975,      0,      0,   5526,      0,
         93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
             0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
        119513,      0,      0,      0,      0,      0, 118895,  48509,
        100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
         54395,  26731,  44329, 118236, 113808,    610,      0,      0,
         12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
             0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
        110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
         26544,  52596,  47503,  89056,  28834, 110564,  56638, 

In [51]:
km_anos.T

array([[ 44410,   2003,   2467],
       [  5712,   1991,    190],
       [ 37123,   1990,   1197],
       [     0,   2019,      0],
       [ 25757,   2006,   1717],
       [ 10728,   2012,   1192],
       [     0,   2019,      0],
       [ 77599,   2009,   6466],
       [ 99197,   2010,   9017],
       [ 37978,   2011,   3797],
       [ 12859,   2002,    676],
       [  8052,   2007,    575],
       [ 89773,   2001,   4488],
       [     0,   2019,      0],
       [ 41457,   2009,   3454],
       [115607,   2016,  23121],
       [ 46449,   2012,   5161],
       [     0,   2019,      0],
       [ 37086,   2016,   7417],
       [ 15173,   2017,   3793],
       [101193,   2002,   5325],
       [     0,   2019,      0],
       [ 98079,   1994,   3632],
       [102959,   1991,   3431],
       [     0,   2019,      0],
       [     0,   2019,      0],
       [  5795,   2016,   1159],
       [     0,   2019,      0],
       [ 58848,   2002,   3097],
       [ 94381,   1991,   3146],
       [ 3

In [52]:
valor = np.loadtxt('carros-valor.txt', dtype = float)

In [53]:
carros_data = np.column_stack((anos, km, valor)) #transforma arrays unidimensionais em colunas

In [54]:
carros_data

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [56]:
np.mean(carros_data[:, 2]) #media dos valores

98960.51310077519

In [58]:
carros_data[:, 1].sum() #soma das quilometragens poderia ser np.sum(carros_data[:, 1])

11480849.0